import type { Handler } from "@netlify/functions";
import { WebSocket as NodeWebSocket } from "ws";
import { createClient } from "@supabase/supabase-js";
import { SLUG_RE } from "./_shared/landing-page";

// See connect-telegram.ts for why this polyfill is needed (Node <22 has no
// global WebSocket, which @supabase/supabase-js requires internally).
if (typeof globalThis.WebSocket === "undefined") {
  (globalThis as unknown as { WebSocket: unknown }).WebSocket = NodeWebSocket;
}

const supabaseUrl = process.env.SUPABASE_URL!;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// Both ids are generated by the landing page itself (LandingPage.tsx).
const ID_RE = /^[A-Za-z0-9_-]{8,64}$/;
// Longer than anyone genuinely reads a landing; a tab left open for a day
// would otherwise drag the average time on page into nonsense.
const MAX_DURATION_MS = 30 * 60 * 1000;
// Link-preview fetchers and crawlers load the page too; they are stored (so a
// sudden spike stays explainable) but left out of every count.
const BOT_RE = /bot|crawl|spider|slurp|preview|facebookexternalhit|facebot|headless|lighthouse|pingdom|curl|wget|python-requests|httpclient/i;

/**
 * Public, unauthenticated — the landing page's own visit counter, feeding
 * landing_analytics (the Аналітика page and the landing card's popup).
 *   { type: "start", slug, visitId, visitorId }  — page loaded
 *   { type: "time",  slug, visitId, durationMs }  — visible time so far,
 *     sent via sendBeacon whenever the page is hidden (tab switch, close,
 *     the jump into the messenger), so it only ever grows.
 * The org and landing come from the published page's own row, never from the
 * body. Always answers 204: a counting failure must never look like a broken page.
 */
export const handler: Handler = async (event) => {
  const done = { statusCode: 204, body: "" };
  if (event.httpMethod !== "POST") return { statusCode: 405, body: "" };

  let body: { type?: string; slug?: string; visitId?: string; visitorId?: string; durationMs?: number };
  try {
    body = JSON.parse(event.body || "{}");
  } catch {
    return done;
  }

  const slug = (body.slug ?? "").toLowerCase();
  const visitId = body.visitId ?? "";
  if (!SLUG_RE.test(slug) || !ID_RE.test(visitId)) return done;

  const supabase = createClient(supabaseUrl, serviceRoleKey, { auth: { autoRefreshToken: false, persistSession: false } });

  const { data: page, error: pageError } = await supabase
    .from("landing_pages")
    .select("id, org_id")
    .eq("slug", slug)
    .eq("status", "published")
    .maybeSingle();
  if (pageError) console.error("landing-visit: landing lookup failed", pageError);
  if (!page) return done;

  if (body.type === "start") {
    const visitorId = body.visitorId ?? "";
    if (!ID_RE.test(visitorId)) return done;
    const userAgent = event.headers["user-agent"] ?? event.headers["User-Agent"] ?? "";
    const { error } = await supabase.from("landing_visits").upsert(
      {
        org_id: page.org_id,
        landing_page_id: page.id,
        visit_id: visitId,
        visitor_id: visitorId,
        is_bot: !userAgent || BOT_RE.test(userAgent),
      },
      { onConflict: "visit_id", ignoreDuplicates: true },
    );
    if (error) console.error("landing-visit: insert failed", error);
    return done;
  }

  if (body.type === "time") {
    const duration = Math.round(Number(body.durationMs));
    if (!Number.isFinite(duration) || duration <= 0) return done;
    // Scoped to this landing's row, and only ever raised: a replayed or stale
    // beacon can't shrink a visit or touch another landing's visits.
    const { error } = await supabase
      .from("landing_visits")
      .update({ duration_ms: Math.min(duration, MAX_DURATION_MS) })
      .eq("visit_id", visitId)
      .eq("landing_page_id", page.id)
      .lt("duration_ms", Math.min(duration, MAX_DURATION_MS));
    if (error) console.error("landing-visit: duration update failed", error);
  }

  return done;
};
